CREATE SCHEMA IF NOT EXISTS product;

CREATE TABLE IF not EXISTS product.product
(
    id                 bigint generated BY DEFAULT AS identity NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    unit_price         DECIMAL(10, 2)                          NOT NULL,
    quantity_total     DECIMAL(10, 3)                          NOT NULL,
    quantity_reserved  DECIMAL(10, 3),
    created_date       timestamptz                             NOT NULL,
    updated_date       timestamptz,
    CONSTRAINT product_pk PRIMARY KEY (id)
);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Felix Cat food - meat', 1.10, 100, 15, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Feline fare - salmon', 20.10, 56, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Feline fare - chicken', 15.10, 32, 15, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Feline fare - Meat', 25.00, 20, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Feline fare - Turkey', 20.10, 56, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Purrfect paws - salmon', 19.00, 13, 11, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Purrfect paws - chicken', 17.30, 32, 15, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Purrfect paws - Meat', 25.00, 20, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Purrfect paws - Turkey', 20.10, 56, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Meow market - salmon', 19.00, 13, 12, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Meow market - chicken', 17.30, 32, 15, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Meow market - Meat', 25.00, 20, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Meow market - Turkey', 20.10, 56, 10, now(), null);

INSERT INTO product.product (name, unit_price, quantity_total, quantity_reserved, created_date, updated_date)
VALUES ('Meow market - Cat scratcher', 114.32, 10, 3, now(), null);