CREATE SCHEMA IF NOT EXISTS sales_order;

CREATE TABLE IF not EXISTS sales_order.purchase_order
(
    id           bigint generated BY DEFAULT AS identity NOT NULL,
    client_id    bigint                                  NOT NULL,
    total_amount DECIMAL(10, 3)                          NOT NULL,
    created_date timestamptz                             NOT NULL,
    updated_date timestamptz,
    CONSTRAINT purchase_order_pk PRIMARY KEY (id)
);

CREATE TABLE IF not EXISTS sales_order.purchase_order_item
(
    id                bigint generated BY DEFAULT AS identity NOT NULL,
    purchase_order_id bigint                                  NOT NULL REFERENCES sales_order.purchase_order (id),
    product_id        bigint                                  NOT NULL,
    quantity          DECIMAL(10, 3)                          NOT NULL,
    price_item        DECIMAL(10, 3)                          NOT NULL,
    total_price       DECIMAL(10, 3)                          NOT NULL,
    CONSTRAINT purchase_order_item_pk PRIMARY KEY (id)
);